name: Event Dispatcher

on:
  repository_dispatch:
    types: [Post Infrastructure Apply]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: "echo ${{ toJSON(github) }}"
  dispatch_first:
    name: 'Dispatch First Deployment'
    if: |
      github.event.action == 'Post Infrastructure Apply' && (
        github.event.client_payload.first.changed  == 'true' ||
        github.event.client_payload.github.changed    == 'true' ||
        github.event.client_payload.common.changed    == 'true'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch First Continuous Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: First Continuous Deployment

  dispatch_second:
    name: 'Dispatch Second Deployment'
    if: |
      github.event.action == 'Post Infrastructure Apply' && (
        github.event.client_payload.second.changed    == 'true' ||
        github.event.client_payload.github.changed    == 'true' ||
        github.event.client_payload.common.changed    == 'true'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch First Continuous Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: Second Continuous Deployment