name: First Continuous Deployment

# Only run this workflow once the Terraform Apply workflow has completed.
on:
  workflow_run:
    workflows: [Terraform Apply]
    types:
      - completed

# Only run one workflow at a time that has the `coordination-deploy` group.
concurrency:
  group: coordination-deploy

jobs:
  print:
    name: 'Print'
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Path: ${{ github.event_path }}"
          echo "Event File: ${{ github.event_file }}"
          echo "API URL: ${{ github.api_url }}"

  # Only run the remaining jobs in this workflow if files changed in the .github directory or respective project's directory.
  check_changes:
    name: 'Check Changes'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: 7c85a33cb7b54c2cf7587a3563badeffe796b9e1
        filters: |
          src:
            - '.github/**'
            - 'firstpath/**'
  
  set_environment:
    name: 'Set Environment'
    needs: check_changes
    if: ${{ needs.check_changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    steps:
      - id: setenv
        run: |
          if [ "${{github.ref_name}}" == "develop" ]; then 
            echo "my_env=Develop" >> "$GITHUB_OUTPUT";
          fi