name: First Continuous Deployment

# Only run this workflow once the Terraform Apply workflow has completed.
on:
  repository_dispatch:
    types: [dispatch-first]

# Only run one workflow at a time that has the `coordination-deploy` group.
concurrency:
  group: coordination-deploy

jobs:
  
  set_environment:
    name: 'Set Environment'
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    steps:
      - id: setenv
        run: |
          if [ "${{github.ref_name}}" == "develop" ]; then 
            echo "my_env=Develop" >> "$GITHUB_OUTPUT";
          fi