name: 'Terraform Plan'

on:
  pull_request:
    paths: 'terraform/**'

concurrency:
  group: terraform

jobs:
  set_environment:
    name: 'Set Environment'
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.get_environment.outputs.my_env }}
    steps:
      - name: Get Environment
        uses: ./.github/actions/get_environment
        id: get_environment
        with:
          Branch-Name: ${{ github.event.pull_request.base.ref }}

  terraform:
    name: "Terraform Plan"
    needs: set_environment
    runs-on: ubuntu-latest
    steps:
      - run: echo 'terraform plan'