name: Second Continuous Deployment

on:
  repository_dispatch:
    types: [Second Continuous Deployment]

concurrency:
  group: coordination-deploy

jobs:
  set_environment:
    name: 'Set Environment'
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.get_environment.outputs.my_env }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Environment
        uses: ./.github/actions/get_environment
        id: get_environment
        with:
          Branch-Name: ${{ github.ref_name }}